// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20220927153254_SeedsClientes")]
    partial class SeedsClientes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Domain.Entities.Cliente", b =>
                {
                    b.Property<string>("Cpf")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Cpf");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            Cpf = "90406710015",
                            Celular = "1166996699",
                            Nome = "Pumba",
                            UF = "SP"
                        },
                        new
                        {
                            Cpf = "67482339094",
                            Celular = "1165656565",
                            Nome = "Rafiki",
                            UF = "SP"
                        },
                        new
                        {
                            Cpf = "89387788008",
                            Celular = "4155668899",
                            Nome = "Simba",
                            UF = "PR"
                        },
                        new
                        {
                            Cpf = "99927465050",
                            Celular = "1158585858",
                            Nome = "Timão",
                            UF = "SP"
                        },
                        new
                        {
                            Cpf = "27585548010",
                            Celular = "5126262626",
                            Nome = "Zazu",
                            UF = "RS"
                        },
                        new
                        {
                            Cpf = "71676470042",
                            Celular = "1198989898",
                            Nome = "Nala",
                            UF = "SP"
                        },
                        new
                        {
                            Cpf = "83799824014",
                            Celular = "1165686568",
                            Nome = "Mufasa",
                            UF = "SP"
                        },
                        new
                        {
                            Cpf = "30439355001",
                            Celular = "1126232623",
                            Nome = "Scar",
                            UF = "SP"
                        },
                        new
                        {
                            Cpf = "61450660088",
                            Celular = "4166666666",
                            Nome = "Ed",
                            UF = "PR"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Financiamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DataUltimoVencimento")
                        .HasColumnType("datetime2");

                    b.Property<int>("TipoFinanciamento")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasAlternateKey("Cpf");

                    b.ToTable("Financiamentos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cpf = "90406710015",
                            DataUltimoVencimento = new DateTime(2022, 10, 27, 15, 32, 53, 861, DateTimeKind.Utc).AddTicks(3552),
                            TipoFinanciamento = 1,
                            ValorTotal = 5000m
                        },
                        new
                        {
                            Id = 2,
                            Cpf = "67482339094",
                            DataUltimoVencimento = new DateTime(2022, 10, 27, 15, 32, 53, 861, DateTimeKind.Utc).AddTicks(3560),
                            TipoFinanciamento = 1,
                            ValorTotal = 5000m
                        },
                        new
                        {
                            Id = 3,
                            Cpf = "89387788008",
                            DataUltimoVencimento = new DateTime(2022, 10, 27, 15, 32, 53, 861, DateTimeKind.Utc).AddTicks(3561),
                            TipoFinanciamento = 1,
                            ValorTotal = 5000m
                        },
                        new
                        {
                            Id = 4,
                            Cpf = "99927465050",
                            DataUltimoVencimento = new DateTime(2023, 1, 25, 15, 32, 53, 861, DateTimeKind.Utc).AddTicks(3562),
                            TipoFinanciamento = 4,
                            ValorTotal = 5000m
                        },
                        new
                        {
                            Id = 5,
                            Cpf = "27585548010",
                            DataUltimoVencimento = new DateTime(2023, 1, 25, 15, 32, 53, 861, DateTimeKind.Utc).AddTicks(3564),
                            TipoFinanciamento = 4,
                            ValorTotal = 5000m
                        },
                        new
                        {
                            Id = 6,
                            Cpf = "71676470042",
                            DataUltimoVencimento = new DateTime(2023, 1, 25, 15, 32, 53, 861, DateTimeKind.Utc).AddTicks(3566),
                            TipoFinanciamento = 4,
                            ValorTotal = 5000m
                        },
                        new
                        {
                            Id = 7,
                            Cpf = "83799824014",
                            DataUltimoVencimento = new DateTime(2022, 11, 26, 15, 32, 53, 861, DateTimeKind.Utc).AddTicks(3567),
                            TipoFinanciamento = 4,
                            ValorTotal = 5000m
                        },
                        new
                        {
                            Id = 8,
                            Cpf = "30439355001",
                            DataUltimoVencimento = new DateTime(2022, 11, 26, 15, 32, 53, 861, DateTimeKind.Utc).AddTicks(3567),
                            TipoFinanciamento = 4,
                            ValorTotal = 5000m
                        });
                });

            modelBuilder.Entity("Domain.Entities.Parcela", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("DataPagamento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdFinanciamento")
                        .HasColumnType("int");

                    b.Property<int>("NumeroParcela")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorParcela")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdFinanciamento");

                    b.ToTable("Parcelas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataPagamento = new DateTime(2022, 6, 29, 15, 32, 53, 861, DateTimeKind.Utc).AddTicks(3583),
                            DataVencimento = new DateTime(2022, 6, 29, 15, 32, 53, 861, DateTimeKind.Utc).AddTicks(3583),
                            IdFinanciamento = 1,
                            NumeroParcela = 1,
                            ValorParcela = 1000m
                        },
                        new
                        {
                            Id = 2,
                            DataPagamento = new DateTime(2022, 7, 29, 15, 32, 53, 861, DateTimeKind.Utc).AddTicks(3588),
                            DataVencimento = new DateTime(2022, 7, 29, 15, 32, 53, 861, DateTimeKind.Utc).AddTicks(3587),
                            IdFinanciamento = 1,
                            NumeroParcela = 2,
                            ValorParcela = 1000m
                        },
                        new
                        {
                            Id = 3,
                            DataPagamento = new DateTime(2022, 8, 28, 15, 32, 53, 861, DateTimeKind.Utc).AddTicks(3589),
                            DataVencimento = new DateTime(2022, 8, 28, 15, 32, 53, 861, DateTimeKind.Utc).AddTicks(3589),
                            IdFinanciamento = 1,
                            NumeroParcela = 3,
                            ValorParcela = 1000m
                        },
                        new
                        {
                            Id = 4,
                            DataPagamento = new DateTime(2022, 9, 27, 15, 32, 53, 861, DateTimeKind.Utc).AddTicks(3591),
                            DataVencimento = new DateTime(2022, 9, 27, 15, 32, 53, 861, DateTimeKind.Utc).AddTicks(3590),
                            IdFinanciamento = 1,
                            NumeroParcela = 4,
                            ValorParcela = 1000m
                        },
                        new
                        {
                            Id = 5,
                            DataVencimento = new DateTime(2022, 10, 27, 15, 32, 53, 861, DateTimeKind.Utc).AddTicks(3592),
                            IdFinanciamento = 1,
                            NumeroParcela = 5,
                            ValorParcela = 1000m
                        },
                        new
                        {
                            Id = 6,
                            DataPagamento = new DateTime(2022, 7, 29, 15, 32, 53, 861, DateTimeKind.Utc).AddTicks(3593),
                            DataVencimento = new DateTime(2022, 7, 29, 15, 32, 53, 861, DateTimeKind.Utc).AddTicks(3593),
                            IdFinanciamento = 2,
                            NumeroParcela = 1,
                            ValorParcela = 1000m
                        },
                        new
                        {
                            Id = 7,
                            DataPagamento = new DateTime(2022, 8, 28, 15, 32, 53, 861, DateTimeKind.Utc).AddTicks(3594),
                            DataVencimento = new DateTime(2022, 8, 28, 15, 32, 53, 861, DateTimeKind.Utc).AddTicks(3594),
                            IdFinanciamento = 2,
                            NumeroParcela = 2,
                            ValorParcela = 1000m
                        },
                        new
                        {
                            Id = 8,
                            DataPagamento = new DateTime(2022, 9, 26, 15, 32, 53, 861, DateTimeKind.Utc).AddTicks(3596),
                            DataVencimento = new DateTime(2022, 9, 26, 15, 32, 53, 861, DateTimeKind.Utc).AddTicks(3595),
                            IdFinanciamento = 2,
                            NumeroParcela = 3,
                            ValorParcela = 1000m
                        },
                        new
                        {
                            Id = 9,
                            DataVencimento = new DateTime(2022, 10, 27, 15, 32, 53, 861, DateTimeKind.Utc).AddTicks(3598),
                            IdFinanciamento = 2,
                            NumeroParcela = 4,
                            ValorParcela = 1000m
                        },
                        new
                        {
                            Id = 10,
                            DataVencimento = new DateTime(2022, 11, 26, 15, 32, 53, 861, DateTimeKind.Utc).AddTicks(3599),
                            IdFinanciamento = 2,
                            NumeroParcela = 5,
                            ValorParcela = 1000m
                        },
                        new
                        {
                            Id = 11,
                            DataVencimento = new DateTime(2022, 9, 27, 15, 32, 53, 861, DateTimeKind.Utc).AddTicks(3632),
                            IdFinanciamento = 3,
                            NumeroParcela = 1,
                            ValorParcela = 1000m
                        },
                        new
                        {
                            Id = 12,
                            DataVencimento = new DateTime(2022, 10, 27, 15, 32, 53, 861, DateTimeKind.Utc).AddTicks(3633),
                            IdFinanciamento = 3,
                            NumeroParcela = 2,
                            ValorParcela = 1000m
                        },
                        new
                        {
                            Id = 13,
                            DataVencimento = new DateTime(2022, 11, 26, 15, 32, 53, 861, DateTimeKind.Utc).AddTicks(3634),
                            IdFinanciamento = 3,
                            NumeroParcela = 3,
                            ValorParcela = 1000m
                        },
                        new
                        {
                            Id = 14,
                            DataVencimento = new DateTime(2022, 12, 26, 15, 32, 53, 861, DateTimeKind.Utc).AddTicks(3635),
                            IdFinanciamento = 3,
                            NumeroParcela = 4,
                            ValorParcela = 1000m
                        },
                        new
                        {
                            Id = 15,
                            DataVencimento = new DateTime(2023, 1, 25, 15, 32, 53, 861, DateTimeKind.Utc).AddTicks(3636),
                            IdFinanciamento = 3,
                            NumeroParcela = 5,
                            ValorParcela = 1000m
                        },
                        new
                        {
                            Id = 16,
                            DataVencimento = new DateTime(2022, 9, 27, 15, 32, 53, 861, DateTimeKind.Utc).AddTicks(3637),
                            IdFinanciamento = 4,
                            NumeroParcela = 1,
                            ValorParcela = 1000m
                        },
                        new
                        {
                            Id = 17,
                            DataVencimento = new DateTime(2022, 10, 27, 15, 32, 53, 861, DateTimeKind.Utc).AddTicks(3638),
                            IdFinanciamento = 4,
                            NumeroParcela = 2,
                            ValorParcela = 1000m
                        },
                        new
                        {
                            Id = 18,
                            DataVencimento = new DateTime(2022, 11, 26, 15, 32, 53, 861, DateTimeKind.Utc).AddTicks(3639),
                            IdFinanciamento = 4,
                            NumeroParcela = 3,
                            ValorParcela = 1000m
                        },
                        new
                        {
                            Id = 19,
                            DataVencimento = new DateTime(2022, 12, 26, 15, 32, 53, 861, DateTimeKind.Utc).AddTicks(3640),
                            IdFinanciamento = 4,
                            NumeroParcela = 4,
                            ValorParcela = 1000m
                        },
                        new
                        {
                            Id = 20,
                            DataVencimento = new DateTime(2023, 1, 25, 15, 32, 53, 861, DateTimeKind.Utc).AddTicks(3641),
                            IdFinanciamento = 4,
                            NumeroParcela = 5,
                            ValorParcela = 1000m
                        },
                        new
                        {
                            Id = 21,
                            DataVencimento = new DateTime(2022, 9, 27, 15, 32, 53, 861, DateTimeKind.Utc).AddTicks(3641),
                            IdFinanciamento = 5,
                            NumeroParcela = 1,
                            ValorParcela = 1000m
                        },
                        new
                        {
                            Id = 22,
                            DataVencimento = new DateTime(2022, 10, 27, 15, 32, 53, 861, DateTimeKind.Utc).AddTicks(3642),
                            IdFinanciamento = 5,
                            NumeroParcela = 2,
                            ValorParcela = 1000m
                        },
                        new
                        {
                            Id = 23,
                            DataVencimento = new DateTime(2022, 11, 26, 15, 32, 53, 861, DateTimeKind.Utc).AddTicks(3644),
                            IdFinanciamento = 5,
                            NumeroParcela = 3,
                            ValorParcela = 1000m
                        },
                        new
                        {
                            Id = 24,
                            DataVencimento = new DateTime(2022, 12, 26, 15, 32, 53, 861, DateTimeKind.Utc).AddTicks(3645),
                            IdFinanciamento = 5,
                            NumeroParcela = 4,
                            ValorParcela = 1000m
                        },
                        new
                        {
                            Id = 25,
                            DataVencimento = new DateTime(2023, 1, 25, 15, 32, 53, 861, DateTimeKind.Utc).AddTicks(3646),
                            IdFinanciamento = 5,
                            NumeroParcela = 5,
                            ValorParcela = 1000m
                        },
                        new
                        {
                            Id = 26,
                            DataVencimento = new DateTime(2022, 7, 29, 15, 32, 53, 861, DateTimeKind.Utc).AddTicks(3647),
                            IdFinanciamento = 6,
                            NumeroParcela = 1,
                            ValorParcela = 1000m
                        },
                        new
                        {
                            Id = 27,
                            DataVencimento = new DateTime(2022, 8, 28, 15, 32, 53, 861, DateTimeKind.Utc).AddTicks(3649),
                            IdFinanciamento = 6,
                            NumeroParcela = 2,
                            ValorParcela = 1000m
                        },
                        new
                        {
                            Id = 28,
                            DataVencimento = new DateTime(2022, 9, 26, 15, 32, 53, 861, DateTimeKind.Utc).AddTicks(3650),
                            IdFinanciamento = 6,
                            NumeroParcela = 3,
                            ValorParcela = 1000m
                        },
                        new
                        {
                            Id = 29,
                            DataVencimento = new DateTime(2022, 10, 27, 15, 32, 53, 861, DateTimeKind.Utc).AddTicks(3651),
                            IdFinanciamento = 6,
                            NumeroParcela = 4,
                            ValorParcela = 1000m
                        },
                        new
                        {
                            Id = 30,
                            DataVencimento = new DateTime(2022, 11, 26, 15, 32, 53, 861, DateTimeKind.Utc).AddTicks(3652),
                            IdFinanciamento = 6,
                            NumeroParcela = 5,
                            ValorParcela = 1000m
                        },
                        new
                        {
                            Id = 31,
                            DataVencimento = new DateTime(2022, 7, 29, 15, 32, 53, 861, DateTimeKind.Utc).AddTicks(3653),
                            IdFinanciamento = 7,
                            NumeroParcela = 1,
                            ValorParcela = 1000m
                        },
                        new
                        {
                            Id = 32,
                            DataVencimento = new DateTime(2022, 8, 28, 15, 32, 53, 861, DateTimeKind.Utc).AddTicks(3654),
                            IdFinanciamento = 7,
                            NumeroParcela = 2,
                            ValorParcela = 1000m
                        },
                        new
                        {
                            Id = 33,
                            DataVencimento = new DateTime(2022, 9, 26, 15, 32, 53, 861, DateTimeKind.Utc).AddTicks(3655),
                            IdFinanciamento = 7,
                            NumeroParcela = 3,
                            ValorParcela = 1000m
                        },
                        new
                        {
                            Id = 34,
                            DataVencimento = new DateTime(2022, 10, 27, 15, 32, 53, 861, DateTimeKind.Utc).AddTicks(3656),
                            IdFinanciamento = 7,
                            NumeroParcela = 4,
                            ValorParcela = 1000m
                        },
                        new
                        {
                            Id = 35,
                            DataVencimento = new DateTime(2022, 11, 26, 15, 32, 53, 861, DateTimeKind.Utc).AddTicks(3657),
                            IdFinanciamento = 7,
                            NumeroParcela = 5,
                            ValorParcela = 1000m
                        });
                });

            modelBuilder.Entity("Domain.Entities.Financiamento", b =>
                {
                    b.HasOne("Domain.Entities.Cliente", "Cliente")
                        .WithMany("Financiamentos")
                        .HasForeignKey("Cpf")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Domain.Entities.Parcela", b =>
                {
                    b.HasOne("Domain.Entities.Financiamento", "Financiamento")
                        .WithMany("Parcelas")
                        .HasForeignKey("IdFinanciamento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Financiamento");
                });

            modelBuilder.Entity("Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Financiamentos");
                });

            modelBuilder.Entity("Domain.Entities.Financiamento", b =>
                {
                    b.Navigation("Parcelas");
                });
#pragma warning restore 612, 618
        }
    }
}
